FUNCTION_BLOCK "FB_Analog"
VAR_INPUT
  iSysInface : "RCS_SysComInterface_V1";
  "iunit in" : UInt;
  "iunit out" : UInt;
  "iHardware input" : Word;
  iRangeDown : Real;
  iRangeUp : Real;
END_VAR
VAR_IN_OUT
  io_Dev : "ST_GeneralAnalog";
END_VAR
VAR_TEMP
  TmpMidReal0 : Real;
END_VAR
BEGIN
  // Původní jazyk: LAD
  // Zdroj XML: EXPORT/Program blocks/03_Device/212 Analog/FB_Analog.xml
  // (Žádný StructuredText network nebyl nalezen; LAD/STL/GRAPH není automaticky překládán.)
END_FUNCTION_BLOCK
