FUNCTION_BLOCK "FB_Step"
VAR_INPUT
  I_bRun : Bool;
END_VAR
VAR
  sCurrNo : UInt;
  sNextNo : UInt;
  sPls : Bool;
  sCondition : Bool;
  sRunJump : Bool;
  sTON : TON_TIME;
  sDealyTime : Time;
  sTempNo : UInt;
  bInitialization : Bool;
END_VAR
BEGIN
  // Původní jazyk: LAD
  // Zdroj XML: EXPORT/Program blocks/03_Device/999 Base/FB_Step.xml
  // (Žádný StructuredText network nebyl nalezen; LAD/STL/GRAPH není automaticky překládán.)
END_FUNCTION_BLOCK
