FUNCTION_BLOCK "ST10_Flow12_A2TableUnloading"
VAR_INPUT
  iSysInface : "RCS_SysComInterface_V1";
END_VAR
VAR_IN_OUT
  ioPM_Inface : "RCS_PMInterface_V1";
  ioStatus : Int;
END_VAR
VAR
  sCtrlMode : "SysFlowCtrlGraph";
  sUpdMES_Data : Bool;
  "工件放行中" : Bool;
  "前站站号" : UInt;
  "本站站号" : UInt;
  "弹窗Temp" : Array[1..10] of Int;
  AlarmID : Int;
  TON : Array[0..10] of TON_TIME;
  TOF : Array[0..10] of TOF_TIME;
  sUP : Array[0..10] of Bool;
  "更新RFID完成" : Bool;
  RT_DATA : G7_RTDataPlus_V6;
  Trans1 : G7_TransitionPlus_V6;
  Trans2 : G7_TransitionPlus_V6;
  Trans3 : G7_TransitionPlus_V6;
  Trans325 : G7_TransitionPlus_V6;
  Trans4 : G7_TransitionPlus_V6;
  Trans10 : G7_TransitionPlus_V6;
  Trans102 : G7_TransitionPlus_V6;
  Trans17 : G7_TransitionPlus_V6;
  Trans18 : G7_TransitionPlus_V6;
  Trans19 : G7_TransitionPlus_V6;
  Trans20 : G7_TransitionPlus_V6;
  Trans21 : G7_TransitionPlus_V6;
  Trans22 : G7_TransitionPlus_V6;
  Trans23 : G7_TransitionPlus_V6;
  Trans24 : G7_TransitionPlus_V6;
  Trans30 : G7_TransitionPlus_V6;
  Trans31 : G7_TransitionPlus_V6;
  Trans32 : G7_TransitionPlus_V6;
  Trans200 : G7_TransitionPlus_V6;
  Trans101 : G7_TransitionPlus_V6;
  Trans103 : G7_TransitionPlus_V6;
  Trans106 : G7_TransitionPlus_V6;
  Trans107 : G7_TransitionPlus_V6;
  Trans108 : G7_TransitionPlus_V6;
  Trans109 : G7_TransitionPlus_V6;
  Trans110 : G7_TransitionPlus_V6;
  Trans111 : G7_TransitionPlus_V6;
  Trans283 : G7_TransitionPlus_V6;
  Trans113 : G7_TransitionPlus_V6;
  Trans112 : G7_TransitionPlus_V6;
  Trans115 : G7_TransitionPlus_V6;
  Trans765 : G7_TransitionPlus_V6;
  Trans117 : G7_TransitionPlus_V6;
  Trans766 : G7_TransitionPlus_V6;
  Trans119 : G7_TransitionPlus_V6;
  Trans767 : G7_TransitionPlus_V6;
  Trans768 : G7_TransitionPlus_V6;
  Trans769 : G7_TransitionPlus_V6;
  Trans770 : G7_TransitionPlus_V6;
  Trans124 : G7_TransitionPlus_V6;
  Trans125 : G7_TransitionPlus_V6;
  Trans771 : G7_TransitionPlus_V6;
  Trans127 : G7_TransitionPlus_V6;
  Trans128 : G7_TransitionPlus_V6;
  Trans129 : G7_TransitionPlus_V6;
  Trans130 : G7_TransitionPlus_V6;
  Trans131 : G7_TransitionPlus_V6;
  Trans132 : G7_TransitionPlus_V6;
  Trans133 : G7_TransitionPlus_V6;
  Trans134 : G7_TransitionPlus_V6;
  Trans135 : G7_TransitionPlus_V6;
  Trans139 : G7_TransitionPlus_V6;
  Trans140 : G7_TransitionPlus_V6;
  Trans146 : G7_TransitionPlus_V6;
  Trans250 : G7_TransitionPlus_V6;
  Trans613 : G7_TransitionPlus_V6;
  F12_Initial : G7_StepPlus_V6;
  S2 : G7_StepPlus_V6;
  S3 : G7_StepPlus_V6;
  S4 : G7_StepPlus_V6;
  S5_MESInitial : G7_StepPlus_V6;
  "ServoReady?" : G7_StepPlus_V6;
  WaitRobotInitialFinish : G7_StepPlus_V6;
  S10_InitialFinish : G7_StepPlus_V6;
  "Servo returns to1st Pos" : G7_StepPlus_V6;
  ServoPosCount : G7_StepPlus_V6;
  ServoPosCountJudge : G7_StepPlus_V6;
  ServoPosCountClear : G7_StepPlus_V6;
  CountCompare : G7_StepPlus_V6;
  TableLackMaterial : G7_StepPlus_V6;
  WaitFixtureScanFinish : G7_StepPlus_V6;
  ResetPartMissingAlarm : G7_StepPlus_V6;
  ProcessStart : G7_StepPlus_V6;
  WaitChangeOverFinish : G7_StepPlus_V6;
  WaitServoInPosition : G7_StepPlus_V6;
  "Detect cartridge exist" : G7_StepPlus_V6;
  "Detect Ring exist" : G7_StepPlus_V6;
  "Detect UnloadingRing exist" : G7_StepPlus_V6;
  "Detect UnloadingRing exist_1" : G7_StepPlus_V6;
  PartMissingAlarm : G7_StepPlus_V6;
  Step111 : G7_StepPlus_V6;
  "Request robot pick" : G7_StepPlus_V6;
  SensorNoPart : G7_StepPlus_V6;
  CountClear : G7_StepPlus_V6;
  CountClear_1 : G7_StepPlus_V6;
  "A-Loading-02UpDownTakeCylinderToWP" : G7_StepPlus_V6;
  "CheckA-Loading-02HorizontalCylinderPos" : G7_StepPlus_V6;
  "A-Loading-02UpDownTakeCylinderToWP_1" : G7_StepPlus_V6;
  "A-Loading-02HorizontalCylinderToHP" : G7_StepPlus_V6;
  "A-Loading-02UpDownTakeCylinderToHP_2" : G7_StepPlus_V6;
  "A-Loading-02HorizontalCylinderToWP_1" : G7_StepPlus_V6;
  "A-Loading-02UpDownTakeCylinderToHP3" : G7_StepPlus_V6;
  TimDelay : G7_StepPlus_V6;
  TimDelay_1 : G7_StepPlus_V6;
  "A-Loading-02HorizontalCylinderToHP_1" : G7_StepPlus_V6;
  ServoNeedMove : G7_StepPlus_V6;
  "No cartridge" : G7_StepPlus_V6;
  "No Ring" : G7_StepPlus_V6;
  "Clearing mode?" : G7_StepPlus_V6;
  "Wait  robot finish task" : G7_StepPlus_V6;
  WaitChangeOverOK : G7_StepPlus_V6;
  WaitEmptyFinish : G7_StepPlus_V6;
  "Process Finish" : G7_StepPlus_V6;
END_VAR
VAR_TEMP
  Tempresult : USInt;
  "本站站号乘10" : UInt;
END_VAR
BEGIN
  // Původní jazyk: GRAPH
  // Zdroj XML: EXPORT/Program blocks/OP010/03_Auto/A2_TableLoad&Scan/ST10_Flow12_A2TableUnloading.xml
  // (Nebylo nalezeno StructuredText/FlgNet/StatementList; logika může být v GRAPH nebo v nepodporované reprezentaci.)
END_FUNCTION_BLOCK
