DATA_BLOCK "AutoProcessControl"
VAR
  A_Table_1Scan : STRUCT
    Robot1PickPrimit : Bool;
    Spare_2 : Bool;
    Spare_3 : Bool;
    Spare_4 : Bool;
    Spare_5 : Bool;
    Spare_6 : Bool;
    Spare_7 : Bool;
    Spare_8 : Bool;
    Spare_9 : Bool;
    Spare_10 : Bool;
    Spare_11 : Bool;
    Spare_12 : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    Spare_16 : Bool;
  END_STRUCT;
  A_Table_1Loading : STRUCT
    Robot1PickPrimit : Bool;
    Spare_2 : Bool;
    Spare_3 : Bool;
    Spare_4 : Bool;
    Spare_5 : Bool;
    Spare_6 : Bool;
    Spare_7 : Bool;
    Spare_8 : Bool;
    Spare_9 : Bool;
    Spare_10 : Bool;
    Spare_11 : Bool;
    Spare_12 : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    Spare_16 : Bool;
    ServoRunCount : Int;
  END_STRUCT;
  A_Table_2Scan : STRUCT
    Robot3PickPrimit : Bool;
    Spare_2 : Bool;
    Spare_3 : Bool;
    Spare_4 : Bool;
    Spare_5 : Bool;
    Spare_6 : Bool;
    Spare_7 : Bool;
    Spare_8 : Bool;
    Spare_9 : Bool;
    Spare_10 : Bool;
    Spare_11 : Bool;
    Spare_12 : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    Spare_16 : Bool;
  END_STRUCT;
  A_Table_2Loading : STRUCT
    Robot3PickPrimit : Bool;
    Spare_2 : Bool;
    Spare_3 : Bool;
    Spare_4 : Bool;
    Spare_5 : Bool;
    Spare_6 : Bool;
    Spare_7 : Bool;
    Spare_8 : Bool;
    Spare_9 : Bool;
    Spare_10 : Bool;
    Spare_11 : Bool;
    Spare_12 : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    Spare_16 : Bool;
    ServoRunCount : Int;
  END_STRUCT;
  A_ScanRotary : STRUCT
    Robot1PickPrimit : Bool;
    Robot1PutPrimit : Bool;
    Spare_3 : Bool;
    Spare_4 : Bool;
    Spare_5 : Bool;
    Spare_6 : Bool;
    Spare_7 : Bool;
    Spare_8 : Bool;
    Spare_9 : Bool;
    Spare_10 : Bool;
    Spare_11 : Bool;
    Spare_12 : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    Spare_16 : Bool;
  END_STRUCT;
  B_Press_1 : STRUCT
    Robot1PickPrimit : Bool;
    Robot1PutShaftPrimit : Bool;
    Robot1PutRingPrimit : Bool;
    Spare_4 : Bool;
    Spare_5 : Bool;
    Spare_6 : Bool;
    Spare_7 : Bool;
    Spare_8 : Bool;
    Spare_9 : Bool;
    Spare_10 : Bool;
    Spare_11 : Bool;
    Spare_12 : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    Spare_16 : Bool;
    GripStatus : Int;
  END_STRUCT;
  B_Press_2 : STRUCT
    Robot3PickPrimit : Bool;
    Robot3PutRingPrimit : Bool;
    Robot2PutPrimit : Bool;
    Spare_4 : Bool;
    Spare_5 : Bool;
    Spare_6 : Bool;
    Spare_7 : Bool;
    Spare_8 : Bool;
    Spare_9 : Bool;
    Spare_10 : Bool;
    Spare_11 : Bool;
    Spare_12 : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    Spare_16 : Bool;
    GripStatus : Int;
  END_STRUCT;
  C_Glue : STRUCT
    Robot2PickPrimit : Bool;
    Robot1PutPrimit : Bool;
    Robot2MaganePutPrimit : Bool;
    Spare_4 : Bool;
    Spare_5 : Bool;
    Spare_6 : Bool;
    Spare_7 : Bool;
    Spare_8 : Bool;
    GlueTest : Bool;
    Spare_10 : Bool;
    Spare_11 : Bool;
    Spare_12 : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    Spare_16 : Bool;
  END_STRUCT;
  H_ShafeLine : STRUCT
    Robot1PickPrimit : Bool;
    Spare_2 : Bool;
    Spare_3 : Bool;
    Spare_4 : Bool;
    Spare_5 : Bool;
    Spare_6 : Bool;
    Spare_7 : Bool;
    Spare_8 : Bool;
    EmptyMaterial : Bool;
    LineTest : Bool;
    Spare_11 : Bool;
    Spare_12 : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    Spare_16 : Bool;
  END_STRUCT;
  J_MagnetLine : STRUCT
    Robot2PickPrimit : Bool;
    Spare_2 : Bool;
    Spare_3 : Bool;
    Spare_4 : Bool;
    Spare_5 : Bool;
    Spare_6 : Bool;
    Spare_7 : Bool;
    Spare_8 : Bool;
    EmptyMaterial : Bool;
    LineTest : Bool;
    Spare_11 : Bool;
    Spare_12 : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    Spare_16 : Bool;
  END_STRUCT;
  K_ShafeLine : STRUCT
    Robot2PickPrimit : Bool;
    Spare_2 : Bool;
    Spare_3 : Bool;
    Spare_4 : Bool;
    Spare_5 : Bool;
    Spare_6 : Bool;
    Spare_7 : Bool;
    Spare_8 : Bool;
    EmptyMaterial : Bool;
    LineTest : Bool;
    Spare_11 : Bool;
    Spare_12 : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    Spare_16 : Bool;
  END_STRUCT;
  L_ShafeLine : STRUCT
    Robot3PutPrimit : Bool;
    Spare_2 : Bool;
    Spare_3 : Bool;
    Spare_4 : Bool;
    Spare_5 : Bool;
    Spare_6 : Bool;
    Spare_7 : Bool;
    Spare_8 : Bool;
    EmptyMaterial : Bool;
    LineTest : Bool;
    Spare_11 : Bool;
    Spare_12 : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    Spare_16 : Bool;
  END_STRUCT;
  Headt : STRUCT
    PalletUnloadingPrimit : Bool;
    Spare_2 : Bool;
    Spare_3 : Bool;
    Spare_4 : Bool;
    Spare_5 : Bool;
    Spare_6 : Bool;
    Spare_7 : Bool;
    Spare_8 : Bool;
    Spare_9 : Bool;
    Spare_10 : Bool;
    Spare_11 : Bool;
    Spare_12 : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    Spare_16 : Bool;
  END_STRUCT;
  Robot2ScanNG : STRUCT
    PutPrimit : Bool;
    Spare_2 : Bool;
    Spare_3 : Bool;
    Spare_4 : Bool;
    Spare_5 : Bool;
    Spare_6 : Bool;
    Spare_7 : Bool;
    Spare_8 : Bool;
    Spare_9 : Bool;
    Spare_10 : Bool;
    Spare_11 : Bool;
    Spare_12 : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    Spare_16 : Bool;
  END_STRUCT;
  Robot2GlueNG : STRUCT
    PutPrimit : Bool;
    Spare_2 : Bool;
    Spare_3 : Bool;
    Spare_4 : Bool;
    Spare_5 : Bool;
    Spare_6 : Bool;
    Spare_7 : Bool;
    Spare_8 : Bool;
    Spare_9 : Bool;
    Spare_10 : Bool;
    Spare_11 : Bool;
    Spare_12 : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    Spare_16 : Bool;
  END_STRUCT;
  NG_1 : STRUCT
    Robot1PutPrimit_1 : Bool;
    Robot1PutPrimit_2 : Bool;
    Robot1PutPrimit_3 : Bool;
    Spare_4 : Bool;
    Spare_5 : Bool;
    Spare_6 : Bool;
    Spare_7 : Bool;
    Spare_8 : Bool;
    DoorRequest : Bool;
    Spare_10 : Bool;
    Spare_11 : Bool;
    Spare_12 : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    Spare_16 : Bool;
  END_STRUCT;
  NG_2 : STRUCT
    Robot3PutPrimit_1 : Bool;
    Robot3PutPrimit_2 : Bool;
    Robot3PutPrimit_3 : Bool;
    Spare_4 : Bool;
    Spare_5 : Bool;
    Spare_6 : Bool;
    Spare_7 : Bool;
    Spare_8 : Bool;
    DoorRequest : Bool;
    Spare_10 : Bool;
    Spare_11 : Bool;
    Spare_12 : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    Spare_16 : Bool;
  END_STRUCT;
  NGBuffer : STRUCT
    Robot3PPickMagnetNGPrimit : Bool;
    PickGlueNGPrimit : Bool;
    Spare_17 : Bool;
    Spare_4 : Bool;
    Spare_5 : Bool;
    Spare_6 : Bool;
    Spare_7 : Bool;
    Spare_8 : Bool;
    Spare_9 : Bool;
    Spare_10 : Bool;
    Spare_11 : Bool;
    Spare_12 : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    Spare_16 : Bool;
  END_STRUCT;
  Fixture1Code : STRUCT
    Robot1CodeReadReq : Bool;
    Spare_17 : Bool;
    Spare_18 : Bool;
    Spare_4 : Bool;
    Spare_5 : Bool;
    Spare_6 : Bool;
    Spare_7 : Bool;
    Spare_8 : Bool;
    Spare_9 : Bool;
    Spare_10 : Bool;
    Spare_11 : Bool;
    Spare_12 : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    Spare_16 : Bool;
  END_STRUCT;
  Fixture2Code : STRUCT
    Robot3CodeReadReq : Bool;
    Spare_17 : Bool;
    Spare_18 : Bool;
    Spare_4 : Bool;
    Spare_5 : Bool;
    Spare_6 : Bool;
    Spare_7 : Bool;
    Spare_8 : Bool;
    Spare_9 : Bool;
    Spare_10 : Bool;
    Spare_11 : Bool;
    Spare_12 : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    Spare_16 : Bool;
  END_STRUCT;
  Robot_1 : STRUCT
    GluePutFlag : Bool;
    NGPutFlag : Bool;
    MaintenanceRequest : Bool;
    HomeRequest : Bool;
    Spare_5 : Bool;
    Spare_6 : Bool;
    Spare_7 : Bool;
    Spare_8 : Bool;
    ReadyToRobot2 : Bool;
    ClearPart : Bool;
    GripScanRequest : Bool;
    OnePart : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    Spare_16 : Bool;
  END_STRUCT;
  Robot_2 : STRUCT
    PalletPickFlag : Bool;
    MagnetScanFlag : Bool;
    GluePutFlag : Bool;
    GluePickFlag : Bool;
    Press2PutFlag : Bool;
    GlueNGPutFlag : Bool;
    ScanNGPutFlag : Bool;
    Spare_8 : Bool;
    ReadyToRobot1 : Bool;
    ReadyToRobot3 : Bool;
    MaintenanceRequest : Bool;
    HomeRequest : Bool;
    GripScanRequest : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    Spare_16 : Bool;
  END_STRUCT;
  Robot_3 : STRUCT
    Press2PutFlag : Bool;
    Press2PickFlag : Bool;
    GlueNGPickFlag : Bool;
    ScanNGPickFlag : Bool;
    NGPutFlag : Bool;
    Spare_10 : Bool;
    Spare_9 : Bool;
    Spare_8 : Bool;
    ReadyToRobot2 : Bool;
    PalletFull : Bool;
    MaintenanceRequest : Bool;
    HomeRequest : Bool;
    GripScanRequest : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    Spare_16 : Bool;
  END_STRUCT;
  Global : STRUCT
    H : STRUCT
      EmptyPallet : Bool;
      LoadStopRequestPallet_1 : Bool;
      LoadStopRequestPallet_2 : Bool;
      LoadStopRequestPallet_3 : Bool;
      LoadStopRequestPallet_4 : Bool;
      EmptyStopRequestPallet_1 : Bool;
      EmptyStopRequestPallet_2 : Bool;
      EmptyStopRequestPallet_3 : Bool;
      Spare : Bool;
      Spare_1 : Bool;
      Spare_2 : Bool;
      Spare_3 : Bool;
      Spare_4 : Bool;
      Spare_5 : Bool;
      Spare_6 : Bool;
      Spare_7 : Bool;
    END_STRUCT;
    J : STRUCT
      EmptyPallet : Bool;
      LoadStopRequestPallet_1 : Bool;
      LoadStopRequestPallet_2 : Bool;
      LoadStopRequestPallet_3 : Bool;
      LoadStopRequestPallet_4 : Bool;
      EmptyStopRequestPallet_1 : Bool;
      EmptyStopRequestPallet_2 : Bool;
      EmptyStopRequestPallet_3 : Bool;
      Spare : Bool;
      Spare_1 : Bool;
      Spare_2 : Bool;
      Spare_3 : Bool;
      Spare_4 : Bool;
      Spare_5 : Bool;
      Spare_6 : Bool;
      Spare_7 : Bool;
    END_STRUCT;
    K : STRUCT
      EmptyPallet : Bool;
      LoadStopRequestPallet_1 : Bool;
      LoadStopRequestPallet_2 : Bool;
      LoadStopRequestPallet_3 : Bool;
      LoadStopRequestPallet_4 : Bool;
      EmptyStopRequestPallet_1 : Bool;
      EmptyStopRequestPallet_2 : Bool;
      EmptyStopRequestPallet_3 : Bool;
      Spare : Bool;
      Spare_1 : Bool;
      Spare_2 : Bool;
      Spare_3 : Bool;
      Spare_4 : Bool;
      Spare_5 : Bool;
      Spare_6 : Bool;
      Spare_7 : Bool;
    END_STRUCT;
    L : STRUCT
      EmptyPallet : Bool;
      LoadStopRequestPallet_1 : Bool;
      LoadStopRequestPallet_2 : Bool;
      LoadStopRequestPallet_3 : Bool;
      LoadStopRequestPallet_4 : Bool;
      EmptyStopRequestPallet_1 : Bool;
      EmptyStopRequestPallet_2 : Bool;
      EmptyStopRequestPallet_3 : Bool;
      Spare : Bool;
      Spare_1 : Bool;
      Spare_2 : Bool;
      Spare_3 : Bool;
      Spare_4 : Bool;
      Spare_5 : Bool;
      Spare_6 : Bool;
      Spare_7 : Bool;
    END_STRUCT;
    H_EmptyPallet : Bool;
    J_EmptyPallet : Bool;
    K_EmptyPallet : Bool;
    L_EmptyPallet : Bool;
    ALL_EmptyPallet : Bool;
    ALL_BeltPalletEmptyFinish : Bool;
    Spare_7 : Bool;
    Spare_8 : Bool;
    Spare_9 : Bool;
    Spare_10 : Bool;
    Spare_11 : Bool;
    Spare_12 : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    Spare_16 : Bool;
    P : Array[0..60] of Bool;
  END_STRUCT;
  P : Array[0..40] of Bool;
  Status : STRUCT
    A1TableScan : STRUCT
      Status : Int;
    END_STRUCT;
    A1TableUnloading : STRUCT
      Status : Int;
    END_STRUCT;
    A1RotaryScan : STRUCT
      Status : Int;
    END_STRUCT;
    B1Press : STRUCT
      Status : Int;
    END_STRUCT;
    FRobot_1 : STRUCT
      Status : Int;
    END_STRUCT;
    A1FixtureCodeScan : STRUCT
      Status : Int;
    END_STRUCT;
    CGlueing : STRUCT
      Status : Int;
    END_STRUCT;
    FRobot_2 : STRUCT
      Status : Int;
    END_STRUCT;
    A2TableScan : STRUCT
      Status : Int;
    END_STRUCT;
    A2TableUnloading : STRUCT
      Status : Int;
    END_STRUCT;
    ChangeOver : STRUCT
      Status : Int;
    END_STRUCT;
    B2Press : STRUCT
      Status : Int;
    END_STRUCT;
    FRobot_3 : STRUCT
      Status : Int;
    END_STRUCT;
    A2FixtureCodeScan : STRUCT
      Status : Int;
    END_STRUCT;
    HShaftLifting : STRUCT
      Status : Int;
    END_STRUCT;
    JMagnetLifting : STRUCT
      Status : Int;
    END_STRUCT;
    KReserveLifting : STRUCT
      Status : Int;
    END_STRUCT;
    LUnloadingTrans : STRUCT
      Status : Int;
    END_STRUCT;
    "HShaftLoad&Unload" : STRUCT
      Status : Int;
    END_STRUCT;
    "JMagnetLoad&Unload" : STRUCT
      Status : Int;
    END_STRUCT;
    "KReserveLoad&Unload" : STRUCT
      Status : Int;
    END_STRUCT;
    "LUnloadingLoad&Unload" : STRUCT
      Status : Int;
    END_STRUCT;
    Solidify : STRUCT
      Status : Int;
    END_STRUCT;
    ENG_1 : STRUCT
      Status : Int;
    END_STRUCT;
    ENG_2 : STRUCT
      Status : Int;
    END_STRUCT;
  END_STRUCT;
END_VAR
BEGIN
END_DATA_BLOCK
