DATA_BLOCK "AutoProcessData_Buffer"
VAR
  DataBuffer : Array[0..55] of "ProcessData";
  DataBuffer_1 : "ProcessData";
  DataBuffer_2 : "ProcessData";
  DataBuffer_3 : "ProcessData";
  DataBuffer_4 : "ProcessData";
  DataBuffer_5 : "ProcessData";
  DataBuffer_6 : "ProcessData";
  VAL : Int;
  SelectButton : Int;
  Button_2 : Bool;
  Button_3 : Bool;
  Button_4 : Bool;
  Button_5 : Bool;
  Button_6 : Bool;
END_VAR
BEGIN
END_DATA_BLOCK
