DATA_BLOCK "GluingControl"
VAR
  Input : STRUCT
    GluingDeviceReady : Bool;
    GluingFault : Bool;
    GluingRefillTank : Bool;
    GluingTankEmpty : Bool;
  END_STRUCT;
  Output : STRUCT
    GluingPro_X : Bool;
    GluingPro_Y : Bool;
    GluingPro_Z : Bool;
    GluingReset : Bool;
  END_STRUCT;
  Control : STRUCT
    Manual_X : Bool;
    Manual_Y : Bool;
    Manual_Z : Bool;
    Manual_Control : Int;
    Auto_Start : Bool;
    Auto_Y : Bool;
    Auto_Z : Bool;
    Auto_Control : Int;
    ManualTest_X : Bool;
    ManualTestStartGlue : Bool;
  END_STRUCT;
  GlueCalibratonMode : Bool;
  TON : Array[1..10] of IEC_LTIMER;
  P : Array[1..10] of Bool;
  GlueInitiaStart : Bool;
END_VAR
BEGIN
END_DATA_BLOCK
