DATA_BLOCK "MES_CheckControl"
VAR
  ST1MesCheckIn : Bool;
  ST1MesCheckOut : Bool;
  ST2MesCheckIn : Bool;
  ST2MesCheckOut : Bool;
  ST3MesCheckIn : Bool;
  ST3MesCheckOut : Bool;
  ST4MesCheckIn : Bool;
  ST4MesCheckOut : Bool;
  Station1 : STRUCT
    CheckInRequest : Bool;
    CheckResultRequest : Bool;
  END_STRUCT;
  Station2 : STRUCT
    CheckInRequest : Bool;
    CheckResultRequest : Bool;
  END_STRUCT;
  Station3 : STRUCT
    CheckInRequest : Bool;
    CheckResultRequest : Bool;
  END_STRUCT;
  Station4 : STRUCT
    CheckInRequest : Bool;
    CheckResultRequest : Bool;
  END_STRUCT;
  Station5 : STRUCT
    CheckInRequest : Bool;
    CheckResultRequest : Bool;
  END_STRUCT;
  Station6 : STRUCT
    CheckInRequest : Bool;
    CheckResultRequest : Bool;
  END_STRUCT;
  Station7 : STRUCT
    CheckInRequest : Bool;
    CheckResultRequest : Bool;
  END_STRUCT;
END_VAR
BEGIN
END_DATA_BLOCK
