DATA_BLOCK "OP010_MES_RecipeDB"
VAR
  Download : Bool;
  Downloading : Bool;
  LastTypeID : Int;
  DownloadDone : Bool;
  ParameterElement : STRUCT
    TypeName : String[50];
    TypeID : USInt;
    B1PressProgram : Int;
    B2PressProgram : Int;
    CGlueShaftIV3Program_1 : Word;
    CGlueShaftIV3Program_2 : Word;
    CGlueShaftIV3Program_3 : Word;
    CGlueShaftIV3Program_4 : Word;
    CGlueMagnetIV3Program : Word;
    CGlueProgram : Int;
  END_STRUCT;
END_VAR
BEGIN
END_DATA_BLOCK
