DATA_BLOCK "PalletNGData"
VAR
  LoadingNGPallet : STRUCT
    NG_1_1 : Bool;
    NG_1_2 : Bool;
    NG_1_3 : Bool;
    NG_1_4 : Bool;
    NG_1_5 : Bool;
    NG_2_1 : Bool;
    NG_2_2 : Bool;
    NG_2_3 : Bool;
    NG_2_4 : Bool;
    NG_2_5 : Bool;
    NG_3_1 : Bool;
    NG_3_2 : Bool;
    NG_3_3 : Bool;
    NG_3_4 : Bool;
    NG_3_5 : Bool;
    OpenFlag : Bool;
    Status_1 : Int;
    Status_2 : Int;
    Status_3 : Int;
    Ready_1 : Bool;
    Ready_2 : Bool;
    Ready_3 : Bool;
    Ready_4 : Bool;
    Ready_5 : Bool;
    Ready_6 : Bool;
    Ready : Bool;
    Interlock_1 : Array[1..10] of Bool;
    Interlock_2 : Array[1..10] of Bool;
    Interlock_3 : Array[1..10] of Bool;
    LockStatus : Int;
  END_STRUCT;
  UnLoadingNGPallet : STRUCT
    NG_1_1 : Bool;
    NG_1_2 : Bool;
    NG_1_3 : Bool;
    NG_1_4 : Bool;
    NG_1_5 : Bool;
    NG_2_1 : Bool;
    NG_2_2 : Bool;
    NG_2_3 : Bool;
    NG_2_4 : Bool;
    NG_2_5 : Bool;
    NG_3_1 : Bool;
    NG_3_2 : Bool;
    NG_3_3 : Bool;
    NG_3_4 : Bool;
    NG_3_5 : Bool;
    OpenFlag : Bool;
    Status_1 : Int;
    Status_2 : Int;
    Status_3 : Int;
    Ready_1 : Bool;
    Ready_2 : Bool;
    Ready_3 : Bool;
    Ready_4 : Bool;
    Ready_5 : Bool;
    Ready_6 : Bool;
    Ready : Bool;
    Interlock_1 : Array[1..10] of Bool;
    Interlock_2 : Array[1..10] of Bool;
    Interlock_3 : Array[1..10] of Bool;
    LockStatus : Int;
  END_STRUCT;
  P : Array[0..10] of Bool;
END_VAR
BEGIN
END_DATA_BLOCK
