DATA_BLOCK "PalletRelease"
VAR
  Buffer : STRUCT
    AskPallet : Bool;
    UnloadFlag : Bool;
  END_STRUCT;
  LaserMarking : STRUCT
    AskPallet : Bool;
    UnloadFlag : Bool;
  END_STRUCT;
  Print : STRUCT
    AskPallet : Bool;
    UnloadFlag : Bool;
  END_STRUCT;
  Spare : STRUCT
    AskPallet : Bool;
    UnloadFlag : Bool;
  END_STRUCT;
  Spare2 : STRUCT
    AskPallet : Bool;
    UnloadFlag : Bool;
  END_STRUCT;
  Time : Array[0..1] of TOF_TIME;
  LaserMarkingBuffer : "LaserMarkingBuffer";
END_VAR
BEGIN
END_DATA_BLOCK
