DATA_BLOCK "Parameter"
VAR
  AxisRun : STRUCT
    Axis : Array[1..15] of "ServoType_UDT";
  END_STRUCT;
  AxisNuw : STRUCT
    Axis : Array[1..15] of "ServoType_UDT";
  END_STRUCT;
  AxisDisplay : STRUCT
    Axis : Array[1..15] of "ServoType_UDT";
  END_STRUCT;
  AxisSave : STRUCT
    Axis : Array[1..15] of "ServoType_UDT";
  END_STRUCT;
  AxisStore : Array[1..15] of Struct;
END_VAR
BEGIN
END_DATA_BLOCK
