DATA_BLOCK "PLCtoMES"
VAR
  "PLC.Load_Station1ChickInReq" : Bool;
  "PLC.Load_Station2ChickInReq" : Bool;
  "PLC.Load_Station3ChickInReq" : Bool;
  "PLC.Load_Station4ChickInReq" : Bool;
  "PLC.Load_Station5ChickInReq" : Bool;
  "PLC.Load_Station6ChickInReq" : Bool;
  "PLC.Load_Station7ChickInReq" : Bool;
  "PLC.Load_Station8ChickInReq" : Bool;
  "PLC.Load_StoveCheckIn" : Bool;
  Spare_11 : Bool;
  Spare_12 : Bool;
  Spare_13 : Bool;
  Spare_14 : Bool;
  Spare_15 : Bool;
  Spare_16 : Bool;
  Spare_17 : Bool;
  Spare_18 : Bool;
  Spare_19 : Bool;
  Spare_20 : Bool;
  Spare_21 : Bool;
  Spare_22 : Bool;
  Spare_23 : Bool;
  Spare_24 : Bool;
  Spare_25 : Bool;
  Spare_1 : Byte;
  Spare_2 : Bool;
  Spare_3 : Bool;
  Spare_4 : Bool;
  Spare_5 : Bool;
  Spare_6 : Bool;
  Spare_7 : Bool;
  Spare_8 : Bool;
  Spare_9 : Bool;
  Spare_10 : Bool;
  Static_2 : Bool;
  "PLC.Unload_Station1DataSaveReq" : Bool;
  "PLC.Unload_Station2DataSaveReq" : Bool;
  "PLC.Unload_Station3DataSaveReq" : Bool;
  "PLC.Unload_Station4DataSaveReq" : Bool;
  "PLC.Unload_Station5DataSaveReq" : Bool;
  "PLC.Unload_Station6DataSaveReq" : Bool;
  "PLC.Unload_Station7DataSaveReq" : Bool;
  "PLC.Unload_Station8DataSaveReq" : Bool;
  "PLC.Unload_HeartbeatSignal" : Bool;
END_VAR
BEGIN
END_DATA_BLOCK
