DATA_BLOCK "ProcessData_1"
VAR
  AlwaysZero : Byte;
  "OP40.2" : STRUCT
    Kistler_Continue_Interlock : Bool;
    Kistler_Interlock : Bool;
    KistlerPress_autoInterlock : Bool;
    KistlerPress_1Flag : Bool;
    KistlerPress_2Flag : Bool;
    KistlerPress_1Flag_Reset : Bool;
    KistlerPress_2Flag_Reset : Bool;
    Spare_7 : Bool;
    Spare_8 : Bool;
    Spare_9 : Bool;
    Spare_10 : Bool;
    Spare_11 : Bool;
    Spare_12 : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
  END_STRUCT;
  "OP40.3" : STRUCT
    Kistler_Continue_Interlock : Bool;
    Kistler_Interlock : Bool;
    KistlerPress_autoInterlock : Bool;
    KistlerPress_1Flag : Bool;
    KistlerPress_2Flag : Bool;
    KistlerPress_1Flag_Reset : Bool;
    KistlerPress_2Flag_Reset : Bool;
    Spare_7 : Bool;
    Spare_8 : Bool;
    Spare_9 : Bool;
    Spare_10 : Bool;
    Spare_11 : Bool;
    Spare_12 : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
  END_STRUCT;
  "HMI_OP40.2" : "OP40_Data";
  "HMI_OP40.3" : "OP40_Data";
  PressInterlock_1 : Array[0..15] of Bool;
  PressInterlock_2 : Array[0..15] of Bool;
  Calibartion_1 : Bool;
  Calibartion_2 : Bool;
END_VAR
BEGIN
END_DATA_BLOCK
