DATA_BLOCK "Robot_DB"
VAR
  LoadNG_1 : Array[1..5] of Bool;
  LoadNG_2 : Array[1..5] of Bool;
  LoadNG_3 : Array[1..5] of Bool;
  UnLoadNG_1 : Array[1..5] of Bool;
  UnLoadNG_2 : Array[1..5] of Bool;
  UnLoadNG_3 : Array[1..5] of Bool;
  P : Array[1..16] of Bool;
  RobotFlag_1 : Array[1..8] of Bool;
  RobotFlag_2 : Array[1..8] of Bool;
  RobotFlag_3 : Array[1..8] of Bool;
  RobotSpeed : Array[1..8] of USInt;
  TON : Array[1..18] of TON_TIME;
  Control : STRUCT
    Robot1GripControl : Bool;
    Robot2GripControl : Bool;
    Robot3GripControl : Bool;
  END_STRUCT;
  Robot_1 : STRUCT
    PalletCount_1 : Int;
    GripCompareCodeOK_1 : Bool;
    GripCompareCodeOK_2 : Bool;
    GripCompareCodeOK_3 : Bool;
    GripCompareCodeOK_4 : Bool;
    GripCompareCodeOK : Bool;
    Spare_8 : Bool;
    Spare_6 : Bool;
    Spare_7 : Bool;
    SpeedChangeFlag : Bool;
    MasteringTest_Req : Bool;
    BrakeTest_Req : Bool;
    Spare_11 : Bool;
    Spare_12 : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    SpeedCount : Int;
  END_STRUCT;
  Robot_2 : STRUCT
    PalletCount_1 : Int;
    PalletCount_2 : Int;
    GripCompareCodeOK_1 : Bool;
    GripCompareCodeOK_2 : Bool;
    GripCompareCodeOK_3 : Bool;
    GripCompareCodeOK_4 : Bool;
    GripCompareCodeOK : Bool;
    Spare_5 : Bool;
    Spare_6 : Bool;
    Spare_7 : Bool;
    SpeedChangeFlag : Bool;
    MasteringTest_Req : Bool;
    BrakeTest_Req : Bool;
    Spare_11 : Bool;
    Spare_12 : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    SpeedCount : Int;
  END_STRUCT;
  Robot_3 : STRUCT
    PalletCount_1 : Int;
    PalletCount_2 : Int;
    GripCompareCodeOK_1 : Bool;
    GripCompareCodeOK_2 : Bool;
    GripCompareCodeOK_3 : Bool;
    GripCompareCodeOK_4 : Bool;
    GripCompareCodeOK : Bool;
    Spare_5 : Bool;
    Spare_6 : Bool;
    Spare_7 : Bool;
    SpeedChangeFlag : Bool;
    MasteringTest_Req : Bool;
    BrakeTest_Req : Bool;
    Spare_11 : Bool;
    Spare_12 : Bool;
    Spare_13 : Bool;
    Spare_14 : Bool;
    Spare_15 : Bool;
    SpeedCount : Int;
  END_STRUCT;
END_VAR
BEGIN
END_DATA_BLOCK
