DATA_BLOCK "ST10_SafetyGate_InterfaceDB"
VAR
  aDev : Array[1..20] of "SafetyGateUDT";
  SafetyDoorLamp : Array[1..20] of Bool;
  H : STRUCT
    Status_1 : Int;
    Status_2 : Int;
    Status_3 : Int;
    p : Array[0..20] of Bool;
  END_STRUCT;
  J : STRUCT
    Status_1 : Int;
    Status_2 : Int;
    Status_3 : Int;
    p : Array[0..20] of Bool;
  END_STRUCT;
  K : STRUCT
    Status_1 : Int;
    Status_2 : Int;
    Status_3 : Int;
    p : Array[0..20] of Bool;
  END_STRUCT;
  L : STRUCT
    Status_1 : Int;
    Status_2 : Int;
    Status_3 : Int;
    p : Array[0..20] of Bool;
  END_STRUCT;
END_VAR
BEGIN
END_DATA_BLOCK
