DATA_BLOCK "ST10_PLC_GetDB"
VAR
  InData : STRUCT
    Global : STRUCT
      Beat : Bool;
      AutoRunning : Bool;
      Alarm : Bool;
      SystemStandby : Bool;
      AutoMode : Bool;
      ManualMode : Bool;
      Spare_4 : Bool;
      Spare_5 : Bool;
      Spare_6 : Bool;
      Spare_7 : Bool;
      Spare_8 : Bool;
      Spare_9 : Bool;
      Spare_10 : Bool;
      Spare_11 : Bool;
      Spare_12 : Bool;
      Spare_13 : Bool;
    END_STRUCT;
    Control : STRUCT
      AskPallet : Bool;
      PalletInPos : Bool;
      Spare_1 : Bool;
      Spare_2 : Bool;
      Spare_3 : Bool;
      Spare_4 : Bool;
      Spare_5 : Bool;
      Spare_6 : Bool;
      Spare_7 : Bool;
      Spare_8 : Bool;
      Spare_9 : Bool;
      Spare_10 : Bool;
      Spare_11 : Bool;
      Spare_12 : Bool;
      Spare_13 : Bool;
      Spare_14 : Byte;
      Spare_15 : Byte;
    END_STRUCT;
    Data : STRUCT
      CurrentTemperature_1 : Int;
      CurrentTemperature_2 : Int;
      SetTemperature : Int;
      SetSolidifyTime : Int;
      ActualSolidifyTime : Int;
      Spare_3 : Array[0..83] of Byte;
    END_STRUCT;
  END_STRUCT;
END_VAR
BEGIN
END_DATA_BLOCK
