DATA_BLOCK "ST10_GlobalError"
VAR
  COM : STRUCT
    MainPneumaticPressure1NOK : Bool;
    MainPneumaticPressure2NOK : Bool;
    MainPneumaticPressure3NOK : Bool;
    StationNotInHP : Bool;
    CabinetTemperatureNotOk : Bool;
    CoolingUnitNotOk : Bool;
    RotateTablePositionNOK : Bool;
    RotateTableNotInPosition : Bool;
    StationHardwareError : Bool;
    ChangeStyleError : Bool;
    Reserve3 : Bool;
    Reserve4 : Bool;
    Reserve5 : Bool;
    Reserve6 : Bool;
    Reserve7 : Bool;
    Reserve8 : Bool;
    Reserve : Array[1..4, 0..15] of Bool;
  END_STRUCT;
  Hardware : STRUCT
    PNSlaveStation01 : Array[1..10] of Struct;
    COMM : Array[1..5] of Struct;
    PNSlaveStation02 : Array[1..10] of Struct;
    PNSlaveStation03 : Array[1..10] of Struct;
    ValveIsland : Array[1..5] of Struct;
  END_STRUCT;
  Safety : STRUCT
    "Robot 1 Estop" : Bool;
    "Robot 2 Estop" : Bool;
    HMIEstopPBActivated : Bool;
    TableEstopPB1Activated : Bool;
    TableEstopPB2Activated : Bool;
    TableEstopPB3Activated : Bool;
    TableEstopPB4Activated : Bool;
    TableEstopPB5Activated : Bool;
    TableEstopPB6Activated : Bool;
    EStopSafety : Bool;
    TableEstopPB7Activated : Bool;
    TableEstopPB8Activated : Bool;
    TableEstopPB9Activated : Bool;
    StoveEstopActivated : Bool;
    "Robot 3 Estop" : Bool;
    Reserve9 : Bool;
    Reserve : Array[1..4, 0..15] of Bool;
  END_STRUCT;
  SafetyDoor : STRUCT
    Type : Array[1..5] of Struct;
    No : Array[1..9] of Struct;
    MaterialDoor : STRUCT
      NotLock_1 : Bool;
      NotClose_1 : Bool;
      NotLock_2 : Bool;
      NotClose_2 : Bool;
      NotLock_3 : Bool;
      NotClose_3 : Bool;
      NotLock_4 : Bool;
      NotClose_4 : Bool;
      NotLock_5 : Bool;
      NotClose_5 : Bool;
      NotLock_6 : Bool;
      NotClose_6 : Bool;
      NotLock_7 : Bool;
      NotClose_7 : Bool;
      NotLock_8 : Bool;
      NotClose_8 : Bool;
    END_STRUCT;
  END_STRUCT;
  LightCurtain : Array[1..5] of Struct;
  Product : Array[1..5] of Struct;
  Fixture : Array[1..10] of Struct;
  Breaker : STRUCT
    Trip : Array[1..16] of Bool;
  END_STRUCT;
END_VAR
BEGIN
END_DATA_BLOCK
