DATA_BLOCK "ST10_SysInput"
VAR
  HMI_Button : STRUCT
    ControlOn : Bool;
    ControlOff : Bool;
    MachineStart : Bool;
    MachineStop : Bool;
    ResetButton : Bool;
    "Manual/Auto" : Bool;
    SafetyGateUnlock : Bool;
    "E-Stop" : Bool;
  END_STRUCT;
  Sys : STRUCT
    iCircuitBreakerOK1 : Bool;
    iCircuitBreakerOK2 : Bool;
    iPressure : Bool;
  END_STRUCT;
  "iE-StopPB" : Array[1..20] of Bool;
  iSafetyGatFeedBack : Array[1..20] of Bool;
  iSafetydoorLockingFeedBack : Array[1..20] of Bool;
  iMaterieldoorLockingFeedBack : Array[1..20] of Bool;
END_VAR
BEGIN
END_DATA_BLOCK
