DATA_BLOCK "Station7UnLoadData"
VAR
  "PLC.PartTypeID" : Int;
  "PLC.Station7DMXCode" : String[50];
  "PLC.Station7RecipeNo" : Int;
  "PLC.PartStatus" : Int;
  "PLC.SubPartSN1" : String[50];
  "PLC.TransferTime" : String[50];
  "PLC.Power" : Real;
  "PLC.Displacement" : Real;
  "PLC.Program" : Int;
  "PLC.NGCode" : Int;
  Spare_2 : Byte;
  Spare_3 : Byte;
  Spare_4 : Byte;
  Spare_5 : Byte;
  Spare_6 : Byte;
  Spare_7 : Byte;
  Spare_8 : Byte;
  "MES.ErrorCode" : Int;
  "MES.ErrorMsg" : String[60];
END_VAR
BEGIN
END_DATA_BLOCK
