DATA_BLOCK "Station1UnLoadData"
VAR
  "PLC.PartTypeID" : Int;
  "PLC.Station1DMXCode" : String[128];
  "PLC.Station1RecipeNo" : Int;
  "PLC.PartStatus" : Int;
  "PLC.SubPartSN1" : String[128];
  "PLC.TransferTime" : String[128];
  Spare : Byte;
  Spare_1 : Byte;
  Spare_2 : Byte;
  Spare_3 : Byte;
  Spare_4 : Byte;
  Spare_5 : Byte;
  Spare_6 : Byte;
  Spare_7 : Byte;
  Spare_8 : Byte;
  Spare_9 : Byte;
  Spare_10 : Byte;
  "MES.ErrorCode" : Int;
  "MES.ErrorMsg" : String[128];
END_VAR
BEGIN
END_DATA_BLOCK
