FUNCTION "CylinderModule_V2" : Void
VAR_INPUT
  iReset : Bool;
  iRun : Bool;
  iEStop : Bool;
  iManualMode : Bool;
  iAutoMode : Bool;
  iEnableAlarm : Bool;
  iPulse100mS : Bool;
  iPulse1S : Bool;
  iError : Bool;
  iGoWorkInterlock : Bool;
  iGoHomeInterlock : Bool;
  iWorkPositionSensor : Bool;
  iHomePositionSensor : Bool;
  iValveType : Bool;
  iManualOutputType : Bool;
  iFaultTime : Int;
  iOnPositionTime : Int;
END_VAR
VAR_OUTPUT
  oGoWP_ButtonActive : Bool;
  oGoHP_ButtonActive : Bool;
  oCyNo : Byte;
END_VAR
VAR_IN_OUT
  ioManualGoWork : Bool;
  ioManualGoHome : Bool;
  ioAutoGoWork : Bool;
  ioAutoGoHome : Bool;
  ioResetOut : Bool;
  ioGoWorkTime : Int;
  ioGoHomeTime : Int;
  ioWorkFaultTime : Int;
  ioHomeFaultTime : Int;
  ioBothSensorOnTime : Int;
  ioPulse100mSP : Bool;
  ioAutoGoWorkP : Bool;
  ioAutoGoHomeP : Bool;
  ioGoWork100mSP : Bool;
  ioGoHome100mSP : Bool;
  ioBothSensorOn100mSP : Bool;
  ioAlarm : Bool;
  ioSpare1 : Bool;
  ioSpare2 : Byte;
  ioGoWorkFault : Bool;
  ioGoHomeFault : Bool;
  ioSensorPositionFault : Bool;
  ioGoWorkPosition : Bool;
  ioGoHomePosition : Bool;
END_VAR
BEGIN
  // Původní jazyk: LAD
  // Zdroj XML: EXPORT/Program blocks/03_Device/101_Cylinder/CylinderModule_V2.xml
  // (Žádný StructuredText network nebyl nalezen; LAD/STL/GRAPH není automaticky překládán.)
END_FUNCTION
