FUNCTION "fcFixtureCheck" : Void
VAR_INPUT
  iRecipeSetValue : Byte;
END_VAR
VAR_IN_OUT
  FixtureIDCheck : STRUCT
    FixtureIDSetValue : Int;
    FixtureIDCheckValue : Int;
    FixtureCheckResult : Bool;
    FixtureCheckUnEnable : Bool;
  END_STRUCT;
END_VAR
BEGIN
  // Původní jazyk: LAD
  // Zdroj XML: EXPORT/Program blocks/03_Device/100 FixtureCheck/fcFixtureCheck.xml
  // (Žádný StructuredText network nebyl nalezen; LAD/STL/GRAPH není automaticky překládán.)
END_FUNCTION
