FUNCTION "Robot" : Void
BEGIN
  // Původní jazyk: LAD
  // Zdroj XML: EXPORT/Program blocks/OP010/10_Device/24_Robot/Robot.xml
  // --- Rekonstruovaný StructuredText (best-effort) ---
  // Network 1
  ....KukaRobot1_CtrlDB.sPLCtoROB.User.Home.DI177_NG1_1:=.[] := iE1-UnloadingShaftPressNG_5;
  ....KukaRobot1_CtrlDB.sPLCtoROB.User.Home.DI178_NG1_2:=.[] := iE1-UnloadingShaftPressNG_4;
  ....KukaRobot1_CtrlDB.sPLCtoROB.User.Home.DI179_NG1_3:=.[] := iE1-UnloadingShaftPressNG_3;
  ....KukaRobot1_CtrlDB.sPLCtoROB.User.Home.DI180_NG1_4:=.[] := iE1-UnloadingShaftPressNG_2;
  ....KukaRobot1_CtrlDB.sPLCtoROB.User.Home.DI181_NG1_5:=.[] := iE1-UnloadingShaftPressNG_1;
  
  ....KukaRobot1_CtrlDB.sPLCtoROB.User.Home.DI182_NG2_1:=.[] := iE1-UnloadingShaftScanNG_5;
  ....KukaRobot1_CtrlDB.sPLCtoROB.User.Home.DI183_NG2_2:=.[] := iE1-UnloadingShaftScanNG_4;
  ....KukaRobot1_CtrlDB.sPLCtoROB.User.Home.DI184_NG2_3:=.[] := iE1-UnloadingShaftScanNG_3;
  ....KukaRobot1_CtrlDB.sPLCtoROB.User.Home.DI185_NG2_4:=.[] := iE1-UnloadingShaftScanNG_2;
  ....KukaRobot1_CtrlDB.sPLCtoROB.User.Home.DI186_NG2_5:=.[] := iE1-UnloadingShaftScanNG_1;
  
  ....KukaRobot1_CtrlDB.sPLCtoROB.User.Home.DI187_NG3_1:=.[] := iE1-UnloadingRingScanNG_5;
  ....KukaRobot1_CtrlDB.sPLCtoROB.User.Home.DI188_NG3_2:=.[] := iE1-UnloadingRingScanNG_4;
  ....KukaRobot1_CtrlDB.sPLCtoROB.User.Home.DI189_NG3_3:=.[] := iE1-UnloadingRingScanNG_3;
  ....KukaRobot1_CtrlDB.sPLCtoROB.User.Home.DI190_NG3_4:=.[] := iE1-UnloadingRingScanNG_2;
  ....KukaRobot1_CtrlDB.sPLCtoROB.User.Home.DI191_NG3_5:=.[] := iE1-UnloadingRingScanNG_1;
  // Network 2
  ....KukaRobot3_CtrlDB.sPLCtoROB.User.Home.DI177_PressNG1_1:=.[] := iE2-UnloadingPressNG_5;
  ....KukaRobot3_CtrlDB.sPLCtoROB.User.Home.DI178_PressNG1_2:=.[] := iE2-UnloadingPressNG_4;
  ....KukaRobot3_CtrlDB.sPLCtoROB.User.Home.DI179_PressNG1_3:=.[] := iE2-UnloadingPressNG_3;
  ....KukaRobot3_CtrlDB.sPLCtoROB.User.Home.DI180_PressNG1_4:=.[] := iE2-UnloadingPressNG_2;
  ....KukaRobot3_CtrlDB.sPLCtoROB.User.Home.DI181_PressNG1_5:=.[] := iE2-UnloadingPressNG_1;
  
  ....KukaRobot3_CtrlDB.sPLCtoROB.User.Home.DI182_GlueNG2_1:=.[] := iE2-UnloadingMagentScanNG_5;
  ....KukaRobot3_CtrlDB.sPLCtoROB.User.Home.DI183_GlueNG2_2:=.[] := iE2-UnloadingMagentScanNG_4;
  ....KukaRobot3_CtrlDB.sPLCtoROB.User.Home.DI184_GlueNG2_3:=.[] := iE2-UnloadingMagentScanNG_3;
  ....KukaRobot3_CtrlDB.sPLCtoROB.User.Home.DI185_GlueNG2_4:=.[] := iE2-UnloadingMagentScanNG_2;
  ....KukaRobot3_CtrlDB.sPLCtoROB.User.Home.DI186_GlueNG2_5:=.[] := iE2-UnloadingMagentScanNG_1;
  
  ....KukaRobot3_CtrlDB.sPLCtoROB.User.Home.DI187_ScanNG3_1:=.[] := iE2-UnloadingRingScanNG_5;
  ....KukaRobot3_CtrlDB.sPLCtoROB.User.Home.DI188_ScanNG3_2:=.[] := iE2-UnloadingRingScanNG_4;
  ....KukaRobot3_CtrlDB.sPLCtoROB.User.Home.DI189_ScanNG3_3:=.[] := iE2-UnloadingRingScanNG_3;
  ....KukaRobot3_CtrlDB.sPLCtoROB.User.Home.DI190_ScanNG3_4:=.[] := iE2-UnloadingRingScanNG_2;
  ....KukaRobot3_CtrlDB.sPLCtoROB.User.Home.DI191_ScanNG3_5:=.[] := iE2-UnloadingRingScanNG_1;
END_FUNCTION
