FUNCTION "ST10_Output" : Void
BEGIN
  // Původní jazyk: LAD
  // Zdroj XML: EXPORT/Program blocks/OP010/02_Output/ST10_Output.xml
  // --- Rekonstruovaný StructuredText (best-effort) ---
  // Network 1
  oSafetyDoorLocked_1 := .[];
  oSafetyDoorLocked_2 := .[];
  oSafetyDoorLocked_3 := .[];
  oSafetyDoorLocked_4 := .[];
  oSafetyDoorLocked_5 := .[];
  oSafetyDoorLocked_6 := .[];
  oSafetyDoorLocked_7 := .[];
  oSafetyDoorLocked_8 := .[];
  oSafetyDoorLocked := .[];
  // Network 2
  oMaterielDoorLocked_H1 := .[];
  oMaterielDoorLocked_H2 := .[];
  oMaterielDoorLocked_J1 := .[];
  oMaterielDoorLocked_J2 := .[];
  oMaterielDoorLocked_K1 := .[];
  oMaterielDoorLocked_K2 := .[];
  oMaterielDoorLocked_L1 := .[];
  oE-NG-01SafetyGate := .[];
  oE-NG-02SafetyGate := .[];
END_FUNCTION
