FUNCTION "ST10_Device" : Void
VAR_INPUT
  iSysMode : "RCS_SysComInterface_V1";
END_VAR
BEGIN
  // Původní jazyk: LAD
  // Zdroj XML: EXPORT/Program blocks/OP010/10_Device/ST10_Device.xml
  // --- LAD/FBD → SCL (orientační převod, jen pro revizi) ---
  // Network 1
  // Network 2
  // Network 3
  // Network 4
  // Network 5
  // Network 6
  // Network 7
  // Network 8
  // Network 9
  // Network 10
  // Network 11
  // Network 12
END_FUNCTION
