TYPE "ComponentID_ShW"
STRUCT
  _1 : STRUCT
    name : String[48];
    code : String[48];
    number : DInt;
  END_STRUCT;
  _2 : STRUCT
    name : String[48];
    code : String[48];
    number : DInt;
  END_STRUCT;
  _3 : STRUCT
    name : String[48];
    code : String[48];
    number : DInt;
  END_STRUCT;
  _4 : STRUCT
    name : String[48];
    code : String[48];
    number : DInt;
  END_STRUCT;
  _5 : STRUCT
    name : String[48];
    code : String[48];
    number : DInt;
  END_STRUCT;
  _6 : STRUCT
    name : String[48];
    code : String[48];
    number : DInt;
  END_STRUCT;
  _7 : STRUCT
    name : String[48];
    code : String[48];
    number : DInt;
  END_STRUCT;
  _8 : STRUCT
    name : String[48];
    code : String[48];
    number : DInt;
  END_STRUCT;
  _9 : STRUCT
    name : String[48];
    code : String[48];
    number : DInt;
  END_STRUCT;
  _10 : STRUCT
    name : String[48];
    code : String[48];
    number : DInt;
  END_STRUCT;
END_STRUCT;
END_TYPE
