TYPE "IAI Output Struct"
STRUCT
  "Output 4 word_Man1" : STRUCT
    "Reserve_0.0" : Bool;
    "Reserve_0.1" : Bool;
    "Reserve_0.2" : Bool;
    "Reserve_0.3" : Bool;
    "Reserve_0.4" : Bool;
    "Reserve_0.5" : Bool;
    "Reserve_0.6" : Bool;
    Mon : Bool;
    Reserve_1 : Byte;
    Reserve_2 : Int;
    Reserve_4 : Int;
    Reserve_6 : Int;
  END_STRUCT;
  "Output 4 word_Man2" : STRUCT
    Reserve_8 : Int;
    Reserve_10 : Int;
    Reserve_12 : Int;
    Reserve_14 : Int;
  END_STRUCT;
  "Output 4 word_1" : STRUCT
    "Target position" : DInt;
    "Location Width" : DInt;
  END_STRUCT;
  "Output 4 word_2" : STRUCT
    Speed : Int;
    "Accelerated Speed" : Int;
    "Push Current" : Int;
    "JOG+" : Bool;
    Spare_1 : Bool;
    Spare_2 : Bool;
    Spare_3 : Bool;
    Push : Bool;
    DIR : Bool;
    INC : Bool;
    BKRL : Bool;
    CSTR : Bool;
    Home : Bool;
    STP : Bool;
    RES : Bool;
    SON : Bool;
    JISL : Bool;
    JVEL : Bool;
    "JOG-" : Bool;
  END_STRUCT;
END_STRUCT;
END_TYPE
