TYPE "IAI Input Struct"
STRUCT
  "Input 4 word_Man1" : STRUCT
    "Reserve_0.0" : Bool;
    "Reserve_0.1" : Bool;
    "Reserve_0.2" : Bool;
    "Reserve_0.3" : Bool;
    "Reserve_0.4" : Bool;
    "Reserve_0.5" : Bool;
    "Reserve_0.6" : Bool;
    online : Bool;
    Reserve_Byte_1 : Byte;
    Reserve_Word_2 : Word;
    Reserve_Word_4 : Word;
    Reserve_Word_6 : Word;
  END_STRUCT;
  "Input 4 word_Man2" : STRUCT
    Reserve_Word_8 : Word;
    Reserve_Word_10 : Word;
    Reserve_Word_12 : Word;
    Reserve_Word_14 : Word;
  END_STRUCT;
  "Input 4 word_1" : STRUCT
    "Current Position" : DInt;
    "current value" : DInt;
  END_STRUCT;
  "Input 4 word_2" : STRUCT
    "Current Speed" : Int;
    Reserve_12 : Int;
    "Error Code" : Int;
    MEND : Bool;
    Reserve_9 : Bool;
    Reserve_10 : Bool;
    Reserve_11 : Bool;
    Zone_1 : Bool;
    Zone_2 : Bool;
    CRDY : Bool;
    EMGS : Bool;
    Pend : Bool;
    Hend : Bool;
    Move : Bool;
    ALM : Bool;
    SV : Bool;
    PSFL : Bool;
    Reserve_6 : Bool;
    ALML : Bool;
  END_STRUCT;
END_STRUCT;
END_TYPE
