TYPE "KukaRobot_SysOutput"
STRUCT
  SO : STRUCT
    RC_RDY1 : Bool;
    ALARM_STOP : Bool;
    USER_SAF : Bool;
    PERI_RDY : Bool;
    ROB_CAL : Bool;
    I_O_ACTCONF : Bool;
    STOPMESS : Bool;
    ALARM_STOP_INTERN : Bool;
    PGNO_FBIT_REFL : Byte;
    PRO_ACT : Bool;
    PGNO_REQ : Bool;
    APPL_RUN : Bool;
    PRO_MOVE : Bool;
    IN_HOME : Bool;
    IN_HOME1 : Bool;
    IN_HOME2 : Bool;
    IN_HOME3 : Bool;
    IN_HOME4 : Bool;
    IN_HOME5 : Bool;
    ON_PATH : Bool;
    NEAR_POSRET : Bool;
    ROB_STOPPED : Bool;
    T1 : Bool;
    T2 : Bool;
    AUT : Bool;
    EXT : Bool;
    do_34 : Bool;
    do_35 : Bool;
    do_36 : Bool;
    do_37 : Bool;
    do_38 : Bool;
    do_39 : Bool;
    do_40 : Bool;
    do_41 : Bool;
    do_42 : Bool;
    do_43 : Bool;
    do_44 : Bool;
    do_45 : Bool;
    do_46 : Bool;
    do_47 : Bool;
    do_48 : Bool;
  END_STRUCT;
END_STRUCT;
END_TYPE
