TYPE "PLCtoMES_ST350"
STRUCT
  Common : "PLCtoMES_Common";
  MainCheckIn : "PLCtoMES_MainCheckIn";
  SubCheckIn : "PLCtoMES_SubCheckIn";
  Processing : "PLCtoMES_ProcessingExchange";
  MainCheckOut : "PLCtoMES_MainCheckOut";
  PrintExchange : "PLCtoMES_PrintExchange";
  AGVExchange : "PLCtoMES_AGVExchange";
  ProcessData : "PLCtoMES_MainCheckOutProcessData_OP220";
  AlarmExchange : "PLCtoMES_AlarmExchange";
  RealTimeData : "PLCtoMES_RealTimeData";
END_STRUCT;
END_TYPE
