TYPE "PresserRecipe"
STRUCT
  PressCurveStartPosUL : Real;
  PressCurveStartPosLL : Real;
  PressCurveStartForceUL : Real;
  PressCurveStartForceLL : Real;
  PressCurveMiddlePosUL : Real;
  PressCurveMiddlePosLL : Real;
  PressCurveMiddleForceUL : Real;
  PressCurveMiddleForceLL : Real;
  PressCurveFinalPosUL : Real;
  PressCurveFinalPosLL : Real;
  PressCurveFinalForceUL : Real;
  PressCurveFinalForceLL : Real;
  PresserProgramNum : Int;
END_STRUCT;
END_TYPE
