TYPE "RCS_SysStatus_V1"
STRUCT
  ControlOn : Bool;
  ControlOff : Bool;
  Run : Bool;
  EStopOK : Bool;
  EnableAlarm : Bool;
  Error : Bool;
  FixtureOK : Bool;
  ChangeOverOK : Bool;
  AllDeviceReady : Bool;
  Ready : Bool;
  CanStart : Bool;
  Home : Bool;
  WaitMaterial : Bool;
  LightCurtainOK : Bool;
  SaftyDoorOK : Bool;
  MainPressureOK : Bool;
  ModeSV : Int;
  ModePV : Int;
  FinishProduct : DInt;
END_STRUCT;
END_TYPE
