TYPE "RCS_CountCycleTime_V1"
STRUCT
  Count : STRUCT
    OK : Array[0..14] of DInt;
    NG : Array[0..14] of DInt;
    Total : DInt;
    OKHolding : DInt;
    NGHolding : DInt;
    TotalHolding : DInt;
    ClearOK : Bool;
    ClearNG : Bool;
    ClearTotal : Bool;
  END_STRUCT;
  TotalCycleTime : STRUCT
    No : Array[0..21] of Real;
  END_STRUCT;
  MachineCycleTime : STRUCT
    No : Array[0..21] of Real;
  END_STRUCT;
  Num : USInt;
END_STRUCT;
END_TYPE
