TYPE "RCS_PMInterface_V1"
STRUCT
  Enable : Bool;
  SetInitial : Bool;
  InitialRun : Bool;
  InitialOK : Bool;
  AtHome : Bool;
  SetNextStep : Bool;
  GoNextStep : Bool;
  TriggerOneCycle : Bool;
  WaitRunning : Bool;
  Running : Bool;
  UnPause : Bool;
  ProcessStart : Bool;
  ProcessComplete : Bool;
  Alarm : Bool;
  AlarmImdilyStop : Bool;
  AlarmCycleStop : Bool;
  ProcessStatus : DInt;
  ProcessResult : DInt;
  OperatorPrompt : UInt;
  Num : Int;
  StepNum : Int;
  SpareByte : Array[0..3] of Byte;
END_STRUCT;
END_TYPE
