TYPE "ServoType_UDT"
STRUCT
  Pos1 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos2 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos3 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos4 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos5 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos6 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos7 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos8 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos9 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos10 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos11 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos12 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos13 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos14 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos15 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos16 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos17 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos18 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos19 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos20 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos21 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos22 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos23 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos24 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos25 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos26 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos27 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos28 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos29 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
  Pos30 : STRUCT
    Position : Real;
    Speed : Int;
    Reached : Bool;
  END_STRUCT;
END_STRUCT;
END_TYPE
