TYPE "SubAssemblyID_ShW"
STRUCT
  _1 : STRUCT
    name : String[48];
    code : String[48];
    number : DInt;
  END_STRUCT;
  _2 : STRUCT
    name : String[48];
    code : String[48];
    number : DInt;
  END_STRUCT;
  _3 : STRUCT
    name : String[48];
    code : String[48];
    number : DInt;
  END_STRUCT;
  _4 : STRUCT
    name : String[48];
    code : String[48];
    number : DInt;
  END_STRUCT;
  _5 : STRUCT
    name : String[48];
    code : String[48];
    number : DInt;
  END_STRUCT;
END_STRUCT;
END_TYPE
