TYPE "SubProcessParameterP010_ShW"
STRUCT
  SubProcessParameter : STRUCT
    LowerBearingPressingForce : STRUCT
      LowerBearingPressingForce_value : Real;
      LowerBearingPressingForce_result : Int;
      LowerBearingPressingForce_NG_code : String[9];
    END_STRUCT;
    LowerBearingPressingStroke : STRUCT
      LowerBearingPressingStroke_value : Real;
      LowerBearingPressingStroke_result : Int;
      LowerBearingPressingStroke_NG_code : String[9];
    END_STRUCT;
    UpperBearingPressingForce : STRUCT
      UpperBearingPressingForce_value : Real;
      UpperBearingPressingForce_result : Int;
      UpperBearingPressingForce_NG_code : String[9];
    END_STRUCT;
    UpperBearingPressingStroke : STRUCT
      UpperBearingPressingStroke_value : Real;
      UpperBearingPressingStroke_result : Int;
      UpperBearingPressingStroke_NG_code : String[9];
    END_STRUCT;
    Sleeve1PressingForce : STRUCT
      Sleeve1PressingForce_value : Real;
      Sleeve1PressingForce_result : Int;
      Sleeve1PressingForce_NG_code : String[9];
    END_STRUCT;
    Sleeve1PressingStroke : STRUCT
      Sleeve1PressingStroke_value : Real;
      Sleeve1PressingStroke_result : Int;
      Sleeve1PressingStroke_NG_code : String[9];
    END_STRUCT;
    Sleeve2PressingForce : STRUCT
      Sleeve2PressingForce_value : Real;
      Sleeve2PressingForce_result : Int;
      Sleeve2PressingForce_NG_code : String[9];
    END_STRUCT;
    Sleeve2PressingStroke : STRUCT
      Sleeve2PressingStroke_value : Real;
      Sleeve2PressingStroke_result : Int;
      Sleeve2PressingStroke_NG_code : String[9];
    END_STRUCT;
  END_STRUCT;
END_STRUCT;
END_TYPE
