TYPE "SubProcessParameterP050_ShW"
STRUCT
  SubProcessParameter : STRUCT
    press_force_max_value : STRUCT
      press_force_max_value : Real;
      press_force_max_result : Int;
      press_force_max_NG_code : String[9];
    END_STRUCT;
    displacement_max_value : STRUCT
      displacement_max_value : Real;
      displacement_max_result : Int;
      displacement_max_NG_code : String[9];
    END_STRUCT;
  END_STRUCT;
END_STRUCT;
END_TYPE
