TYPE "TableProcessData"
STRUCT
  PartStatus : Int;
  PartSNGCode : Int;
  PartRemoveFlag : Bool;
  Spare1 : Bool;
  Spare2 : Bool;
  Spare3 : Bool;
  Spare4 : Bool;
  Spare5 : Bool;
  Spare6 : Bool;
  Spare7 : Bool;
  Spare8 : Bool;
  Spare9 : Bool;
  Spare10 : Bool;
  Spare11 : Bool;
  Spare12 : Bool;
  Spare13 : Bool;
  Spare14 : Bool;
  Spare15 : Bool;
  Code : String[128];
  Spare_1 : String[128];
  Spare_2 : String[128];
  Spare_3 : Array[0..51] of Int;
END_STRUCT;
END_TYPE
