TYPE "UDT_PLCtoMES"
STRUCT
  Cmd : STRUCT
    "PLC.Load_ChickIn" : Bool;
    "PLC.Load_1" : Bool;
    "PLC.Load_2" : Bool;
    "PLC.Load_3" : Bool;
    "PLC.Unload_DataSave" : Bool;
    "PLC.Unload_1" : Bool;
    "PLC.Unload_2" : Bool;
    "PLC.Unload_3" : Bool;
    "PLC.Spare8" : Bool;
    "PLC.Spare9" : Bool;
    "PLC.Spare10" : Bool;
    "PLC.Spare11" : Bool;
    "PLC.Spare12" : Bool;
    "PLC.Spare13" : Bool;
    "PLC.Spare14" : Bool;
    "PLC.Spare15" : Bool;
  END_STRUCT;
END_STRUCT;
END_TYPE
