ORGANIZATION_BLOCK "03_CYC_INT2"
VAR_TEMP
  OB32_EV_CLASS : Byte;
  OB32_STRT_INF : Byte;
  OB32_PRIORITY : Byte;
  OB32_OB_NUMBR : Byte;
  OB32_RESERVED_1 : Byte;
  OB32_RESERVED_2 : Byte;
  OB32_PHS_OFFSET : Int;
  OB32_RESERVED_3 : Int;
  OB32_EXC_FREQ : Int;
  OB32_DATE_TIME : Date_And_Time;
END_VAR
BEGIN
  // Původní jazyk: LAD
  // Zdroj XML: EXPORT/Program blocks/01_OB/03_CYC_INT2.xml
  // (Žádný StructuredText network nebyl nalezen; LAD/STL/GRAPH není automaticky překládán.)
END_ORGANIZATION_BLOCK
