ORGANIZATION_BLOCK "04_CYC_INT5"
VAR_TEMP
  OB35_EV_CLASS : Byte;
  OB35_STRT_INF : Byte;
  OB35_PRIORITY : Byte;
  OB35_OB_NUMBR : Byte;
  OB35_RESERVED_1 : Byte;
  OB35_RESERVED_2 : Byte;
  OB35_PHASE_OFFSET : Word;
  OB35_RESERVED_3 : Int;
  OB35_EXC_FREQ : Int;
  OB35_DATE_TIME : Date_And_Time;
END_VAR
BEGIN
  // Původní jazyk: LAD
  // Zdroj XML: EXPORT/Program blocks/01_OB/04_CYC_INT5.xml
  // (Žádný StructuredText network nebyl nalezen; LAD/STL/GRAPH není automaticky překládán.)
END_ORGANIZATION_BLOCK
