ORGANIZATION_BLOCK "05_MOD_ERR"
VAR_TEMP
  OB122_EV_CLASS : Byte;
  OB122_SW_FLT : Byte;
  OB122_PRIORITY : Byte;
  OB122_OB_NUMBR : Byte;
  OB122_BLK_TYPE : Byte;
  OB122_MEM_AREA : Byte;
  OB122_MEM_ADDR : Word;
  OB122_BLK_NUM : Word;
  OB122_PRG_ADDR : Word;
  OB122_DATE_TIME : Date_And_Time;
END_VAR
BEGIN
  // Původní jazyk: STL
  // Zdroj XML: EXPORT/Program blocks/01_OB/05_MOD_ERR.xml
  // (Nebylo nalezeno StructuredText/FlgNet/StatementList; logika může být v GRAPH nebo v nepodporované reprezentaci.)
END_ORGANIZATION_BLOCK
