ORGANIZATION_BLOCK "07_CYCL_FLT"
VAR_TEMP
  OB80_EV_CLASS : Byte;
  OB80_FLT_ID : Byte;
  OB80_PRIORITY : Byte;
  OB80_OB_NUMBR : Byte;
  OB80_RESERVED_1 : Byte;
  OB80_RESERVED_2 : Byte;
  OB80_ERROR_INFO : Word;
  OB80_ERR_EV_CLASS : Byte;
  OB80_ERR_EV_NUM : Byte;
  OB80_OB_PRIORITY : Byte;
  OB80_OB_NUM : Byte;
  OB80_DATE_TIME : Date_And_Time;
END_VAR
BEGIN
  // Původní jazyk: STL
  // Zdroj XML: EXPORT/Program blocks/01_OB/07_CYCL_FLT.xml
  // (Žádný StructuredText network nebyl nalezen; LAD/STL/GRAPH není automaticky překládán.)
END_ORGANIZATION_BLOCK
