ORGANIZATION_BLOCK "08_HW_INT0"
VAR_TEMP
  OB40_EV_CLASS : Byte;
  OB40_STRT_INF : Byte;
  OB40_PRIORITY : Byte;
  OB40_OB_NUMBR : Byte;
  OB40_RESERVED_1 : Byte;
  OB40_IO_FLAG : Byte;
  OB40_MDL_ADDR : Word;
  OB40_POINT_ADDR : DWord;
  OB40_DATE_TIME : Date_And_Time;
END_VAR
BEGIN
  // Původní jazyk: LAD
  // Zdroj XML: EXPORT/Program blocks/01_OB/08_HW_INT0.xml
  // (Žádný StructuredText network nebyl nalezen; LAD/STL/GRAPH není automaticky překládán.)
END_ORGANIZATION_BLOCK
