ORGANIZATION_BLOCK "09_I/O_FLT1"
VAR_TEMP
  OB82_EV_CLASS : Byte;
  OB82_FLT_ID : Byte;
  OB82_PRIORITY : Byte;
  OB82_OB_NUMBR : Byte;
  OB82_RESERVED_1 : Byte;
  OB82_IO_FLAG : Byte;
  OB82_MDL_ADDR : Int;
  OB82_MDL_DEFECT : Bool;
  OB82_INT_FAULT : Bool;
  OB82_EXT_FAULT : Bool;
  OB82_PNT_INFO : Bool;
  OB82_EXT_VOLTAGE : Bool;
  OB82_FLD_CONNCTR : Bool;
  OB82_NO_CONFIG : Bool;
  OB82_CONFIG_ERR : Bool;
  OB82_MDL_TYPE : Byte;
  OB82_SUB_NDL_ERR : Bool;
  OB82_COMM_FAULT : Bool;
  OB82_MDL_STOP : Bool;
  OB82_WTCH_DOG_FLT : Bool;
  OB82_INT_PS_FLT : Bool;
  OB82_PRIM_BATT_FLT : Bool;
  OB82_BCKUP_BATT_FLT : Bool;
  OB82_RESERVED_2 : Bool;
  OB82_RACK_FLT : Bool;
  OB82_PROC_FLT : Bool;
  OB82_EPROM_FLT : Bool;
  OB82_RAM_FLT : Bool;
  OB82_ADU_FLT : Bool;
  OB82_FUSE_FLT : Bool;
  OB82_HW_INTR_FLT : Bool;
  OB82_RESERVED_3 : Bool;
  OB82_DATE_TIME : Date_And_Time;
END_VAR
BEGIN
  // Původní jazyk: STL
  // Zdroj XML: EXPORT/Program blocks/01_OB/09_IO_FLT1.xml
  // (Nebylo nalezeno StructuredText/FlgNet/StatementList; logika může být v GRAPH nebo v nepodporované reprezentaci.)
END_ORGANIZATION_BLOCK
