ORGANIZATION_BLOCK "11_PROG_ERR"
VAR_TEMP
  OB121_EV_CLASS : Byte;
  OB121_SW_FLT : Byte;
  OB121_PRIORITY : Byte;
  OB121_OB_NUMBR : Byte;
  OB121_BLK_TYPE : Byte;
  OB121_RESERVED_1 : Byte;
  OB121_FLT_REG : Word;
  OB121_BLK_NUM : Word;
  OB121_PRG_ADDR : Word;
  OB121_DATE_TIME : Date_And_Time;
END_VAR
BEGIN
  // Původní jazyk: STL
  // Zdroj XML: EXPORT/Program blocks/01_OB/11_PROG_ERR.xml
  // (Nebylo nalezeno StructuredText/FlgNet/StatementList; logika může být v GRAPH nebo v nepodporované reprezentaci.)
END_ORGANIZATION_BLOCK
