ORGANIZATION_BLOCK "12_RACK_FLT"
VAR_TEMP
  OB86_EV_CLASS : Byte;
  OB86_FLT_ID : Byte;
  OB86_PRIORITY : Byte;
  OB86_OB_NUMBR : Byte;
  OB86_RESERVED_1 : Byte;
  OB86_RESERVED_2 : Byte;
  OB86_MDL_ADDR : Word;
  OB86_RACKS_FLTD : Array[0..31] of Bool;
  OB86_DATE_TIME : Date_And_Time;
END_VAR
BEGIN
  // Původní jazyk: STL
  // Zdroj XML: EXPORT/Program blocks/01_OB/12_RACK_FLT.xml
  // (Nebylo nalezeno StructuredText/FlgNet/StatementList; logika může být v GRAPH nebo v nepodporované reprezentaci.)
END_ORGANIZATION_BLOCK
