DATA_BLOCK "KeyenceSR1000Ctrl_807A1DB"
VAR
  sHMI : "RCS_KeyenceSR1000_HMI1";
  sCtrl : STRUCT
    Sequence : Int;
  END_STRUCT;
  sCurrentCode : String[128];
  sInData : "RCS_KeyenceSR1000_Input1";
  sOutData : "RCS_KeyenceSR1000_Output1";
  sAutoOld : Bool;
  sManualOld : Bool;
  sBusyTimeOut : Bool;
  sRunTimer : TON_TIME;
  sBusyTimer : TON_TIME;
  sFindCurrentPos : Int;
END_VAR
BEGIN
END_DATA_BLOCK
