DATA_BLOCK "PartDataManage_Part3_DB"
VAR
  NO : Array[0..6] of Int;
  sString_MId : String;
  sKeyChar : Char;
  Puls : Array[0..20] of Bool;
  R_TRIG_MaterialActive : R_TRIG;
  R_TRIG_ScannerTrigger : R_TRIG;
  IEC_Timer_MaterialActive : TON_TIME;
  R_TRIG_DecrementTrigger : R_TRIG;
  "R_TRIG_PartQuality+1" : R_TRIG;
  "R_TRIG_PartQuality-1" : R_TRIG;
  R_TRIG_ClearCurrentBox : R_TRIG;
  R_TRIG_ClearAllBox : R_TRIG;
  R_TRIG_SaveToBuffer : R_TRIG;
  Timer_PartQualityAckPB : TON_TIME;
END_VAR
BEGIN
END_DATA_BLOCK
