DATA_BLOCK "ST10_CountCycleTimeMain_DB"
VAR
  MianCountCycleTime : "Count_CycleTime";
  PM1CountCycleTime : "Count_CycleTime_V3";
  PM2CountCycleTime : "Count_CycleTime_V3";
  PM3CountCycleTime : "Count_CycleTime_V3";
  PM4CountCycleTime : "Count_CycleTime_V3";
  PM5CountCycleTime : "Count_CycleTime_V3";
  PM6CountCycleTime : "Count_CycleTime_V3";
  PM7CountCycleTime : "Count_CycleTime_V3";
  PM8CountCycleTime : "Count_CycleTime_V3";
  PM9CountCycleTime : "Count_CycleTime_V3";
  PM10CountCycleTime : "Count_CycleTime_V3";
  PM11CountCycleTime : "Count_CycleTime_V3";
  PM12CountCycleTime : "Count_CycleTime_V3";
  PM13CountCycleTime : "Count_CycleTime_V3";
  PM14CountCycleTime : "Count_CycleTime_V3";
  PM15CountCycleTime : "Count_CycleTime_V3";
  PM16CountCycleTime : "Count_CycleTime_V3";
  PM17CountCycleTime : "Count_CycleTime_V3";
  PM18CountCycleTime : "Count_CycleTime_V3";
  PM19CountCycleTime : "Count_CycleTime_V3";
  PM20CountCycleTime : "Count_CycleTime_V3";
  PM21CountCycleTime : "Count_CycleTime_V3";
  PM22CountCycleTime : "Count_CycleTime_V3";
  PM23CountCycleTime : "Count_CycleTime_V3";
  PM24CountCycleTime : "Count_CycleTime_V3";
  PM25CountCycleTime : "Count_CycleTime_V3";
  PM26CountCycleTime : "Count_CycleTime_V3";
  PM27CountCycleTime : "Count_CycleTime_V3";
  PM28CountCycleTime : "Count_CycleTime_V3";
  PM29CountCycleTime : "Count_CycleTime_V3";
  PM30CountCycleTime : "Count_CycleTime_V3";
END_VAR
BEGIN
END_DATA_BLOCK
