DATA_BLOCK "V90Servo_DB"
VAR
  Servo_380A1 : "fbV90Ctrl";
  Servo_381A1 : "fbV90Ctrl";
  Servo_382A1 : "fbV90Ctrl";
  Servo_383A1 : "fbV90Ctrl";
  Servo1 : "SevroStart&PosCheck";
  Servo2 : "SevroStart&PosCheck";
  Servo3 : "SevroStart&PosCheck";
  Servo4 : "SevroStart&PosCheck";
  Servo2SafetyPos : DInt;
  Servo4SafetyPos : DInt;
  IEC_Timer_0_Instance : TON_TIME;
  P : Array[0..10] of Bool;
END_VAR
BEGIN
END_DATA_BLOCK
